### ISSUE TITLE
nextcloud 17

### ISSUE THREAD

**Issue by NoverNobida** [Bekcpear/UMECloudTheme#1]
The theme is beautiful, but I think it can be better. I hope the theme can support nextcloud 17. In fact I use the theme in nextcloud 17, and every thing looks well. But I found a tiny error.
![图片](https://user-images.githubusercontent.com/46912250/70389432-261a5600-19fa-11ea-86f7-3f6cbd7bccde.png)

**Comment by bekcpear** [comment]
It's now compatible with nextcloud 18.0.1.
